version: '2'
services:
  dadget-server:
    image: chipin/rn-mongodb-dadget:v0.1.6-d5
#    deploy:
#      restart_policy:
#        condition: on-failure # version 3 required
    environment:
      - CORE_SERVER=http://test-core.chip-in.net
      - RN_NAME=db-server
      - MONGODB_URL=mongodb://mongodb:27017/
#      - ACCESS_CONTROL_ALLOW_ORIGIN=http://localhost:3000,http://localhost
#      - LOG_LEVEL=info
#      - LOG_MAX_LENGTH=1024
#      - USE_LOG_UPLOADER=true
#      - ACCESS_TOKEN=
#      - TOKEN_UPDATE_PATH=
    extra_hosts:
      - "test-core.chip-in.net:172.17.0.1"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    volumes:
      - ./data/db:/data/db
    command: mongod --logpath=/dev/null
